server:
  port: ${api-gateway.port}
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  profiles:
    active: ${common.env:local}
  config:
    import:
      - optional:classpath:common-service.properties

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
jwt:
  secret: gsdggfsdgddddddddgdsgdghsdrhhshsdghsdsghs
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
